global:
  sequences_file:
  prefix:
bert_embeddings:
  type: embed
  protocol: prottrans_bert_bfd
  reduce: True
  model_directory:
  max_amino_acids:
annotations_from_bert:
  type: extract
  protocol: bert_from_publication
  depends_on: bert_embeddings
  secondary_structure_checkpoint_file:
  subcellular_location_checkpoint_file:
umap_projections:
  type: project
  protocol: umap
  depends_on: bert_embeddings
  n_components: 2
plotly_visualization:
  type: visualize
  protocol: plotly
  display_unknown: True
  depends_on: umap_projections