global:
  sequences_file:
  prefix:
seqvec_embeddings:
  type: embed
  protocol: seqvec
  reduce: True
  weights_file:
  options_file:
  max_amino_acids:
annotations_from_seqvec:
  type: extract
  protocol: seqvec_from_publication
  depends_on: seqvec_embeddings
  secondary_structure_checkpoint_file:
  subcellular_location_checkpoint_file:
umap_projections:
  type: project
  protocol: umap
  depends_on: seqvec_embeddings
  n_components: 2
plotly_visualization:
  type: visualize
  protocol: plotly
  display_unknown: True
  depends_on: umap_projections