# In this example we execute bindEmbed21:
# - First, two MMseqs2 searches are performed and ProtT5 embeddings are generated
# - Second, binding residues are predicted using bindEmbed21 combining homology-based inference and Machine Learning
global:
  # sequences in this file are the "query" sequences
  sequences_file: sequences.fasta
  prefix: bindembed21
# Generate MMseqs2 alignments for bindEmbed21HBI
# The first search searches against a large database of unlabeled sequences and generates profiles of the query sequences
mmseqs_search:
  type: align
  protocol: mmseqs_search
  search_sequences_directory: /path/to/big80
  # Download the pre-computed database from here: http://data.bioembeddings.com/public/embeddings/feature_models/bindembed21/profile_db.tar.gz (~10GB)
  convert_to_profiles: True
  mmseqs_search_options:
    num_iterations: 2
    alignment_output: True
# The second search uses the query profiles to search against a database of sequences with known binding annotations
mmseqs_profile_search:
  type: align
  protocol: mmseqs_search
  # We can selectively chose which parameters to carry over from the "depends_on" stage.
  depends_on:
    # Here, we are interested in the "query_profiles_directory" from the previous search.
    # This parameter stores the path to the directory where the profiles of the query sequences are stored.
    mmseqs_search:
      - query_profiles_directory
  search_sequences_directory: /path/to/lookup
  # Download the pre-computed database from here: http://data.bioembeddings.com/public/embeddings/feature_models/bindembed21/lookup_db.tar.gz
  mmseqs_search_options:
    minimum_sequence_identity: 0.0
    sensitivity: 7.5
    maximum_number_of_prefilter_sequences: 100000
    alignment_output: True
# Generate T5 embeddings for bindEmbed21DL
t5_embeddings:
  type: embed
  protocol: prottrans_t5_xl_u50
  # Uses fp16 instead of fp32 weights (twice as fast)
  half_precision_model: True
  # Stores embeddings in fp16 instead of fp32 (half the storage)
  half_precision: True
  # Keep per-residue embeddings
  reduce: False
bindembed21:
  type: extract
  protocol: bindembed21
  depends_on:
    # This parameter stores the path to the directory where the alignment results of the query sequences are stored
    mmseqs_profile_search:
      - alignment_results_file
    # This parameter stores the path to the directory where the embeddings for the query sequences are stored
    t5_embeddings:
      - embeddings_file

