global:
  # If you provide a url (http, https or ftp), bio_embeddings will download the file for you
  sequences_file: ftp://orengoftp.biochem.ucl.ac.uk/cath/releases/all-releases/v4_2_0/sequence-data/cath-domain-seqs-S35-v4_2_0.fa
  prefix: cath
  simple_remapping: True
seqvec_embeddings:
  type: embed
  protocol: seqvec
  reduce: True
  discard_per_amino_acid_embeddings: True
umap_projections:
  type: project
  protocol: umap
  depends_on: seqvec_embeddings
  n_components: 2
plotly_visualization:
  type: visualize
  protocol: plotly
  annotation_file: cath_classes_S35.csv
  depends_on: umap_projections
